name: CI
on: [push, pull_request, workflow_dispatch]

jobs: # {{{
  ci-build: # {{{

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04

    runs-on: ${{ matrix.os }}

    steps:
      - name: Install Dependencies
        run: sudo apt-get install -y binutils-mingw-w64-i686 gcc-mingw-w64-i686

      - uses: actions/checkout@v3
        with:
          submodules: 'true'

      - uses: iffy/install-nim@v5
        with:
          version: 2.0.2

      - name: Build gta2man
        run: make build
  # }}}
# }}}
